---
- name: "Sistemska priprava: Nadgradnja OS"
  include_tasks: system.yml

- name: "Sistemska priprava: Namestitev Docker okolja"
  include_tasks: docker.yml

- name: "Sistemska priprava: Ustvarjanje /opt imenikov"
  include_tasks: directories.yml
