---
- name: Test 1Password Integration
  hosts: localhost
  tasks:
    - name: Pridobi testno geslo iz 1Password
      debug:
        msg: "Uspešno prebral geslo iz 1Password: {{ lookup('community.general.onepassword', 'Debian Ansible on Laptop P14s', vault='Homelab') }}"
