---
# vps-hardening handlers
- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    daemon_reload: true

- name: reload nftables
  systemd:
    name: nftables
    state: reloaded

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: true
