- name: 'Install python-apt so native apt plugins work'
  package:
    name: 'python-apt'
    state: 'present'
- name: 'Update all packages to the latest version'
  apt:
    upgrade: 'dist'
- name: 'Install pip packages'
  apt:
    name: "{{ packages }}"
- name: 'Pip update pip'
  pip:
    name: 'pip'
    state: 'latest'