[router]
rb4011.kogler.lan

[vps]
vps.kogler.si

[home_servers]
homelab-pc.kogler.lan          # Phase 1: bare-metal Debian desktop
# homelab-ryzen.kogler.lan     # Phase 2: future Proxmox host

[raspberry_pi]
ha-pi.kogler.lan

[docker_hosts:children]
vps
home_servers

[localhost]
localhost ansible_connection=local
