---
- name: Test 1Password Integration
  hosts: localhost
  tasks:
    - name: Fetch test secret from 1Password
      debug:
        msg: "Successfully read password from 1Password: {{ lookup('community.general.onepassword', 'Debian Ansible on Laptop P14s', vault='Homelab') }}"
